### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nmaupu** [nmaupu-org/auto-home#2]
TODO
  - [ ] JDK
  - [ ] intellij
  - [ ] config scratchpad, autosave
  - [ ] gitk ?
  - [ ] enpass
  - [ ] japanese keyboard
  - [x] electricsheep / substrate + config xscreensaver
  - [ ] gimp
  - [ ] virtualbox
  - [ ] vagrant
  - [ ] terraform (several versions ?)
  - [ ] public_html / ready http
  - [ ] keyboard us alt ?
